import type { Metadata } from "next";
import Link from 'next/link';

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
      {/* <p className="text-sm text-gray-500">Background image by <a href="https://www.freepik.com/awesomecontent">awesomecontent</a> on Freepik</p> */}
      <footer className="">
        <div className="flex flex-col items-center justify-center my-32 p-8 mx-32">
          <div className="flex items-center w-full">
            <div className="flex-grow mt-8 border-t border-gray-300"></div> {/* Left line */}
            <p className="text-xl px-12 mb-6">Can't find the word you're looking for?</p>
            <div className="flex-grow mt-8 border-t border-gray-300"></div> {/* Right line */}
          </div>
          
          <strong>
            <button className="border border-teal-600 rounded-sm text-teal-600 text-lg py-2 px-6">Submit a request</button>
          </strong>
        </div>
        
        <div className="flex flex-col items-center justify-center py-2 bg-teal-600 text-white">
          <div className="flex items-center gap-6">
            <img className="w-48 h-14" src="/OrgTionary.svg" alt="orgtionary text" />
            <p>Copyright © 2024 Rosennabs Production.  All rights reserved.</p>
          </div>
          
          <div className="flex gap-6">
            <Link className='link' href='about'>About</Link>
            <span className="text-2xl">|</span>
            <Link className='link' href='glossary'>Glossary</Link>
            <span className="text-2xl">|</span>
            <Link className='link' href='contact'>Contact Us</Link>
          </div>
        </div>
      </footer>
    </html>
  );
}
